#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Generates an index.html file with links to all HTML files in the projects directory
 */
function generateIndex() {
  const projectsDir = path.join(__dirname, 'projects');
  const indexPath = path.join(__dirname, 'index.html');
  
  // Read all files in the projects directory
  const files = fs.readdirSync(projectsDir)
    .filter(file => file.endsWith('.html'))
    .sort();
  
  // Generate project links
  const projectLinks = files.map(file => {
    const fileName = path.basename(file, '.html');
    const displayName = fileName
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
    
    return `        <li><a href="projects/${file}" target="_blank">${displayName}</a></li>`;
  }).join('\n');
  
  // Generate the complete HTML content
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenDemos - Project Index</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #007bff;
            padding-bottom: 10px;
        }
        .project-list {
            list-style: none;
            padding: 0;
        }
        .project-list li {
            margin: 15px 0;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 8px;
            transition: all 0.3s ease;
            border-left: 4px solid #007bff;
        }
        .project-list li:hover {
            background: #e3f2fd;
            transform: translateX(5px);
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .project-list a {
            text-decoration: none;
            color: #007bff;
            font-weight: 500;
            font-size: 16px;
            display: block;
        }
        .project-list a:hover {
            color: #0056b3;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #666;
            font-size: 14px;
        }
        .project-count {
            background: #007bff;
            color: white;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 14px;
            display: inline-block;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>OpenDemos - Project Index</h1>
        <div class="project-count">${files.length} Projects Available</div>
        <ul class="project-list">
${projectLinks}
        </ul>
        <div class="footer">
            <p>Auto-generated by generate-index.js • Last updated: ${new Date().toLocaleString()}</p>
        </div>
    </div>
</body>
</html>`;

  // Write the index.html file
  fs.writeFileSync(indexPath, htmlContent, 'utf8');
  console.log(`✅ Generated index.html with ${files.length} project links`);
  console.log(`📁 Projects found: ${files.join(', ')}`);
}

// Run the generator
if (require.main === module) {
  try {
    generateIndex();
  } catch (error) {
    console.error('❌ Error generating index:', error.message);
    process.exit(1);
  }
}

module.exports = { generateIndex };